### ISSUE TITLE
How to run combine generators? 

### ISSUE THREAD

**Issue by RobberPhex** [amphp/amp#154]
For example:
```php
use Amp\Loop;

Loop::run(function () {
    $httpClient = new Amp\Artax\DefaultClient;

    $uris = [
        "bing" => "http://www.bing.com",
        "yahoo" => "https://www.yahoo.com",
    ];

    $promises = [];
    foreach ($uris as $name => $uri) {
        $promises[$name] = $httpClient->request($uri);
    }
    $responses = yield $promises;

    foreach ($responses as $key => $response) {
        $body = yield $response->getBody();
    }
});
```
it works.

But, when I combine two generator, such as:

```php
use Amp\Loop;

function process($uri, $httpClient){
    $response = yield $httpClient->request($uri);
    $body = yield $response->getBody();

    return substr($body,0,10);
}

Loop::run(function () {
    $httpClient = new Amp\Artax\DefaultClient;

    $uris = [
        "bing" => "http://www.bing.com",
        "yahoo" => "https://www.yahoo.com",
    ];

    $promises = [];
    foreach ($uris as $name => $uri) {
        $promises[$name] = process($uri,$httpClient);
    }
    $res = yield $promises;
    var_dump($res);
});
```

it report error:
```
PHP Fatal error:  Uncaught TypeError: Expected one of the following types: Amp\Promise, React\Promise\PromiseInterface; instance of Generator given in /path/to/proj/vendor/amphp/amp/lib/Internal/functions.php:46
Stack trace:
#0 /path/to/proj/vendor/amphp/amp/lib/functions.php(284): Amp\Internal\createTypeError(Array, Object(Generator))
#1 /path/to/proj/vendor/amphp/amp/lib/Coroutine.php(111): Amp\Promise\all(Array)
#2 /path/to/proj/vendor/amphp/amp/lib/Coroutine.php(90): Amp\Coroutine->transform(Array)
#3 /path/to/proj/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\Coroutine->__construct(Object(Generator))
#4 /path/to/proj/vendor/amphp/amp/lib/Loop/Driver.php(70): Amp\Loop\Driver->tick()
#5 /path/to/proj/vendor/amphp/amp/lib/Loop/EventDriver.php(145): Amp\Loop\Driver->run()
#6 /Users/ro in /path/to/proj/vendor/amphp/amp/lib/Coroutine.php on line 123
```

**How to combine generators?**

**Comment by kelunik** [comment]
You're currently trying to yield a `Generator` instead of a `Promise`, so what you need is turning the `Generator` into a `Promise`. `Amp\call` is the thing you're looking for.

You can either use

```php
foreach ($uris as $name => $uri) {
    $promises[$name] = Amp\call("process", $uri,$httpClient);
}
```

or 

```php
foreach ($uris as $name => $uri) {
    $promises[$name] = new Amp\Coroutine(process($uri,$httpClient));
}
```

However, I'd recommend to not use `Generator`s at API boundaries, because they're an internal implementation detail. Better just use that:

function process($uri, $httpClient): Promise {
    return Amp\call(function () use ($uri, $httpClient) {
        $response = yield $httpClient->request($uri);
        $body = yield $response->getBody();

        return substr($body,0,10);
    });
}

**Comment by trowski** [comment]
@RobberPhex It's worth noting that you can yield another generator within a coroutine by using `yield from` instead of only `yield`. This is primarily useful for reusable private methods, as @kelunik pointed out, APIs should only return promises, not generators.
