### ISSUE TITLE
EventDriver: Event::del(): Failed deletting event

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#159]
`EventDriver` emits warnings for `php examples/1-get-request.php` in `amphp/artax`.

See https://github.com/amphp/artax/issues/131.

**Comment by kelunik** [comment]
I also get another warning with the code from https://github.com/amphp/socket/issues/32: 

```
PHP Warning:  EventBase::loop(): Failed to invoke event callback in /home/kelunik/GitHub/amphp/socket/vendor/amphp/amp/lib/Loop/EventDriver.php on line 178

PHP Fatal error:  Uncaught Amp\Loop\InvalidWatcherError: Cannot enable an invalid watcher identifier: 'cag' in /home/kelunik/GitHub/amphp/socket/vendor/amphp/amp/lib/Loop/Driver.php:369
Stack trace:
#0 /home/kelunik/GitHub/amphp/socket/vendor/amphp/amp/lib/Loop.php(210): Amp\Loop\Driver->enable('cag')
#1 /home/kelunik/GitHub/amphp/socket/vendor/amphp/byte-stream/lib/ResourceOutputStream.php(188): Amp\Loop::enable('cag')
#2 /home/kelunik/GitHub/amphp/socket/vendor/amphp/byte-stream/lib/ResourceOutputStream.php(130): Amp\ByteStream\ResourceOutputStream->send('test', false)
#3 /home/kelunik/GitHub/amphp/socket/lib/Socket.php(67): Amp\ByteStream\ResourceOutputStream->write('test')
#4 /home/kelunik/GitHub/amphp/socket/test.php(35): Amp\Socket\Socket->write('test')
#5 /home/kelunik/GitHub/amphp/socket/vendor/amphp/amp/lib/Loop/EventDriver.php(64): {closure}('cah', NULL)
#6 [internal function]: Amp\Loop\EventDriver->Amp\Loop\{closure}(-1, 1, Object(Amp\Loop\Watcher))
#7 /home/kelunik/GitHub/amphp/socket/vendor/amphp/amp/lib/Loop/Even in /home/kelunik/GitHub/amphp/socket/vendor/amphp/amp/lib/Loop/Driver.php on line 369
```

**Comment by kelunik** [comment]
Fixed via https://github.com/amphp/amp/commit/7a04dc5c21c3433bf16348ff1caaa7fac4cb7a28.
