### ISSUE TITLE
EventDriver Invalid file descriptor

### ISSUE THREAD

**Issue by PNixx** [amphp/amp#344]
```
Fatal error: Uncaught Exception: Invalid file descriptor in /project/vendor/amphp/amp/lib/Loop/EventDriver.php:274
Stack trace:
#0 /project//vendor/amphp/amp/lib/Loop/EventDriver.php(274): Event->__construct(Object(EventBase), Resource id #202, 18, Object(Closure), Object(Amp\Loop\Watcher))
#1 /project/vendor/amphp/amp/lib/Loop/Driver.php(107): Amp\Loop\EventDriver->activate(Array)
#2 /project/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#3 /project/vendor/amphp/amp/lib/Loop/EventDriver.php(206): Amp\Loop\Driver->run()
#4 /project/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\EventDriver->run()
#5 /project/src/Worker/WorkerTrait.php(73): Amp\Loop::run(Array)
#6 /project/bin/server.php(9): Core\Api->onWorkerStarted()
#7 {main}
  thrown in /project/vendor/amphp/amp/lib/Loop/EventDriver.php on line 274
```

```php
trait WorkerTrait {
  ***
  public final function onWorkerStarted() {
    ***
    Loop::run([$this, 'onStart']);
    ***
  }
  public function onStart() {
     $sockets = yield [Cluster::listen('0.0.0.0:' . $this->config['api']['port'])];
     $server = new HttpServer($sockets, new CallableRequestHandler(function(Request $request) {
        ***
     }));
     yield $server->start();
     Cluster::onTerminate(function() use ($server) {
	return $server->stop();
     });
  }
}
```

I try with pecl event 2.5.7 and 3.0.2.

**Comment by enumag** [comment]
Pretty sure this will need more information - full stacktrace (non-vendor classes can be censored ofc) and some sample of your code.

**Comment by PNixx** [comment]
@enumag I updated information a 3 months ago.

**Comment by kelunik** [comment]
I can't reproduce it with the following script derived from your script, so please provide a full runnable example.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

echo Amp\Loop::get()::class;

Amp\Loop::run(function () {
    $sockets = yield [Amp\Cluster\Cluster::listen('0.0.0.0:8000')];
    $server = new Amp\Http\Server\HttpServer($sockets, new Amp\Http\Server\RequestHandler\CallableRequestHandler(function($request) {
        // nothing
    }), new Psr\Log\NullLogger);

    yield $server->start();
    Amp\Cluster\Cluster::onTerminate(function() use ($server) {
    	return $server->stop();
    });
});
```
