### ISSUE TITLE
v3 throw The loop was already running after update to php8.1-rc1 sometimes.

### ISSUE THREAD

**Issue by xpader** [amphp/amp#359]
Before RC1 (beta, alpha) the code running fine, but after update to rc1, v3 throw this exception sometimes in delayd function.

```
Error: The loop was already running in /home/pader/apps/wind-framework-new/example/vendor/amphp/amp/lib/Loop/DriverFoundation.php:64
Stack trace:
#0 /home/pader/apps/wind-framework-new/example/vendor/amphp/amp/lib/Loop.php(402): Amp\Loop\DriverFoundation->run()
#1 [internal function]: Amp\Loop::Amp\{closure}()
#2 /home/pader/apps/wind-framework-new/example/vendor/amphp/amp/lib/functions.php(76): Fiber->start()
#3 /home/pader/apps/wind-framework-new/framework/src/task/Task.php(46): Amp\await(Object(Amp\Internal\PrivatePromise))
#4 /home/pader/apps/wind-framework-new/framework/src/log/AsyncHandler.php(48): Wind\Task\Task::execute(Array, 'app', 'default', 200, 'Hello World', Array)
#5 /home/pader/apps/wind-framework-new/framework/src/log/AsyncHandler.php(30): Wind\Log\AsyncHandler->write(Array)
#6 /home/pader/apps/wind-framework-new/example/vendor/monolog/monolog/src/Monolog/Logger.php(326): Wind\Log\AsyncHandler->handle(Array)
#7 /home/pader/apps/wind-framework-new/example/vendor/monolog/monolog/src/Monolog/Logger.php(520): Monolog\Logger->addRecord(200, 'Hello World', Array)
#8 /home/pader/apps/wind-framework-new/example/app/Controller/TestController.php(67): Monolog\Logger->info('Hello World')
#9 [internal function]: App\Controller\TestController->App\Controller\{closure}()
#10 /home/pader/apps/wind-framework-new/framework/src/base/Amp.php(82): call_user_func_array(Object(Closure), Array)
#11 /home/pader/apps/wind-framework-new/example/vendor/amphp/amp/lib/Loop/NativeDriver.php(103): Wind\Base\Amp->Wind\Base\{closure}('v', NULL)
#12 /home/pader/apps/wind-framework-new/example/vendor/amphp/amp/lib/Loop/DriverFoundation.php(747): Amp\Loop\NativeDriver->dispatch(true)
#13 /home/pader/apps/wind-framework-new/example/vendor/amphp/amp/lib/Loop/DriverFoundation.php(75): Amp\Loop\DriverFoundation->tick()
#14 /home/pader/apps/wind-framework-new/framework/src/base/Amp.php(134): Amp\Loop\DriverFoundation->run()
#15 /home/pader/apps/wind-framework-new/example/vendor/workerman/workerman/Worker.php(2430): Wind\Base\Amp->loop()
#16 /home/pader/apps/wind-framework-new/example/vendor/workerman/workerman/Worker.php(1554): Workerman\Worker->run()
#17 /home/pader/apps/wind-framework-new/example/vendor/workerman/workerman/Worker.php(1384): Workerman\Worker::forkOneWorkerForLinux(Object(Wind\Web\HttpServer))
#18 /home/pader/apps/wind-framework-new/example/vendor/workerman/workerman/Worker.php(1358): Workerman\Worker::forkWorkersForLinux()
#19 /home/pader/apps/wind-framework-new/example/vendor/workerman/workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#20 /home/pader/apps/wind-framework-new/framework/src/base/Application.php(84): Workerman\Worker::runAll()
#21 /home/pader/apps/wind-framework-new/example/start.php(18): Wind\Base\Application::start()
#22 {main}
```

**Comment by xpader** [comment]
After some modify, the code runs ok now, here is the different, it's still strange.

Problem code:
```
    /**
     * Schedule cron timer and run it
     *
     * @param bool $run Run the task at this time
     */
    public function schedule($run=false)
    {
        //计算和安排下一次运行的时间
        $now = new DateTime();
        $nextTimestamp = $this->cronExpression->getNextRunDate($now)->getTimestamp();
        $this->nextRunAt = $nextTimestamp;

        $interval = $nextTimestamp - $now->getTimestamp();
        Timer::add($interval, asyncCallable([$this, 'schedule']), [true], false);

        $this->eventDispatcher->dispatch(new CrontabEvent($this->key, CrontabEvent::TYPE_SCHED, $interval));

        $run && $this->run();
    }

    /**
     * Run the cron task
     */
    public function run()
    {
        $now = time();

        $this->lastRunAt = $now;
        $this->runCount++;

        $this->eventDispatcher->dispatch(new CrontabEvent($this->key, CrontabEvent::TYPE_EXECUTE));

        async('Wind\Task\Task::execute', $this->callback)->onResolve(function($e, $result) {
            /* @var \Exception $e */
            $event = new CrontabEvent($this->key, CrontabEvent::TYPE_RESULT, 0, $e ?: $result);
            $this->eventDispatcher->dispatch($event);
        });
    }

```

No problem code:
```
    /**
     * Schedule cron timer and run it
     *
     * @param bool $run Run the task at this time
     */
    public function schedule($run=false)
    {
        $now = new DateTime();
        $nextTimestamp = $this->cronExpression->getNextRunDate($now)->getTimestamp();
        $this->nextRunAt = $nextTimestamp;

        $interval = $nextTimestamp - $now->getTimestamp();
        Timer::add($interval, asyncCallable([$this, 'schedule']), [true], false);

        $this->eventDispatcher->dispatch(new CrontabEvent($this->key, CrontabEvent::TYPE_SCHED, $interval));

        $run && $this->run();
    }

    /**
     * Run the cron task
     */
    public function run()
    {
        $now = time();
        $this->lastRunAt = $now;
        $this->runCount++;

        $this->eventDispatcher->dispatch(new CrontabEvent($this->key, CrontabEvent::TYPE_EXECUTE));

        $e = $result = null;
        try {
            $result = Task::execute($this->callback);
        } catch (\Throwable $ex) {
            $e = $ex;
        }

        $event = new CrontabEvent($this->key, CrontabEvent::TYPE_RESULT, 0, $e ?: $result);
        $this->eventDispatcher->dispatch($event);
    }
```

The only different is `Task::execute` in or not in `async`.

I can't use some simple code to reproduce that.

**Comment by kelunik** [comment]
I suspect this is due to $this->eventDispatcher->dispatch($event) in the onResolve callback. Try wrapping that with async() as well.

**Comment by xpader** [comment]
Yes, that's exactly why. Thanks.
